### ISSUE TITLE
Week 2 Assignment

### ISSUE THREAD

**Issue by js0101** [biof509/spring2019#3]
I wrote the below code to run the groupby portion, but got 34 and 21 for states_with_more_long_guns 
 and states_with_more_hand_guns respectively. This is incorrect. Is there anything I may be missing?

```python
# YOUR CODE HERE
#(guns.groupby(['state','long_gun'], as_index=False).mean()
            #.groupby('state').mean())
guns_2 = (guns.groupby(['state','handgun'], as_index=False).mean()
            .groupby('state').mean())
states_with_more_long_guns = sum(guns_2['long_gun'] > guns_2['handgun'])
states_with_more_handguns = sum(guns_2['long_gun'] < guns_2['handgun'])
states_with_more_long_guns
#pass
```

**Comment by vinay-swamy** [comment]
So there's no need to groupby twice, and you only need to group by state. Grouping by state and handgun first, taking the mean of that, and then group again by state and taking the mean again is what is causing the problem.
````
guns_2 = guns.groupby(['state']).mean()
````

**Comment by neksa** [comment]
Also the discrepancy may have been caused by an updated dataset. Please see my post in #week2 channel. 
Please download the updated assignment from https://biof509.github.io/spring2019/week2/index.html
Or replace the URL with https://github.com/biof509/spring2019/blob/master/week2/nics-firearm-background-checks.csv?raw=True
